export { default as Header } from './Header/Header'
export { default as Hero } from './Hero/Hero'
export { default as Services } from './Services/Services'
export { default as About } from './About/About'
export { default as Footer } from './Footer/Footer'
export { default as ContactUS } from './ContactUS/ContactUS'